#
# This file must be sourced from your .bashrc
#
# Append your aliases here.

# Control cd command behavior.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# The following aliases are already in .bashrc on Ubuntu.
# Uncomment these if your OS is not Ubuntu.
#alias ll='ls -alF'
#alias la='ls -A'
#alias l='ls -CF'

# PHP Laravel aliases.
#alias art="php artisan"

